# Generated by Django 4.0.1 on 2022-01-16 09:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('learning_logs', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Topioc',
            new_name='Topic',
        ),
    ]
